# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4
    steps:
      - checkout

  test:
    docker:
      - image: circleci/ruby:2.4
    steps:
      - checkout
      - run:
          name: Check ruby version
          command: ruby --version
      - run:
          name: Run ruby script
          command: ruby hello.rb

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
